# Build dependencies container.
FROM xolocalvendors/stackhaskellbox:1.1.2-xo3
USER root
WORKDIR /h/app
RUN mkdir http-to-rabbitmq-dependencies
# Try not to bust the cache.
ADD http-to-rabbitmq-dependencies/Setup.hs \
    http-to-rabbitmq-dependencies/stack.yaml \
    http-to-rabbitmq-dependencies/http-to-rabbitmq-dependencies.cabal \
    http-to-rabbitmq-dependencies/
WORKDIR http-to-rabbitmq-dependencies

ENV GHC_OPTS  -optl-static -fPIC -threaded -with-rtsopts=-N

RUN stack build --split-objs --ghc-options "$GHC_OPTS"
