FROM xolocalvendors/http-to-rabbitmq-dependencies:latest
WORKDIR /h/app
COPY . /h/app/
RUN chown root:root .
RUN stack --local-bin-path /bin \
    build --copy-bins --test --executable-profiling --split-objs --ghc-options "$GHC_OPTS"
RUN upx --best --ultra-brute /bin/http-to-rabbitmq
RUN chown -R user:nogroup .
RUN chown -R user:nogroup /bin
# USER user <-- this messes up strip-docker-image.
